export const UPDATE_FILTER = 'UPDATE_FILTER';
export const SET_LIST_TECHS_BY_FILTER = 'SET_LIST_TECHS_BY_FILTER';
export const ADD_FAVOURITE_TECH = 'ADD_FAVOURITE_TECH';
export const DELETE_FAVOURITE_TECH = 'DELETE_FAVOURITE_TECH';
export const UPDATE_FAVOURITES_TECH = 'UPDATE_FAVOURITES_TECH';
