export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP = 'SIGNUP';
export const UPDATE_FORM = 'UPDATE_FORM';
export const VALIDATE_FORM = 'VALIDATE_FORM';
export const SET_ERRORS = 'SET_ERRORS';
export const SET_REGISTERED_USER = 'SET_REGISTERED_USER';